### ISSUE TITLE
Implement File frontmatter defaults

### ISSUE THREAD

**Issue by hswolff** [reptar/reptar#42]
Pretty much the same idea as https://jekyllrb.com/docs/configuration/#front-matter-defaults

The syntax in the `_config.yml` will be:

```yaml
file:
  defaults:
    -
      scope:
         # Any file in this path will have the default values applied.
         path: './_posts'
         # Any file with this matching metadata will have the default values applied.
         metadata:
           foo: 'bar'
      values:
        template: post
        permalink: /:title/
```
