### ISSUE TITLE
Use an implicit _theme.yml

### ISSUE THREAD

**Issue by hswolff** [reptar/reptar#52]
A goal of mine is to make using Reptar as easy as possible while also being highly customizable.

Right now if you want to create your own theme you _must_ create a `_theme.yml` file to tell Reptar how to read and use your theme.

Perhaps Reptar should use a default `_theme.yml` that lets you create a theme without having to define all the properties.

This file would look like:

``` yaml
name: 'default'

path:
  templates:   ./templates
  plugins:     ./plugins
  destination: ./
```

So you can just create a `_themes/templates` folder and start using templates.

This will let you not worry about configuration and just start theming.

One question I have is what strategy should be used for assets like css and js.

Do you think this helps reduce overhead?
Is this too magical and implicit? 
Is it better to just keep things as is?

**Comment by hswolff** [comment]
To further elaborate, right now in a `_theme.yml` file you configure assets via:

```yaml
assets:
  css:
    source: ./css/main.less
    processor:
      name: less
      hash: true
      plugins:
        autoprefixer:
          browsers: ["last 2 versions"]
        clean-css:

  js:
    source: ./js/main.js
    processor:
      hash: true
      name: browserify
      plugins:
        babelify:
        uglifyify:

  images:
    source: ./images
```

The assets that have a Processor attached are exposed as a [property for any template on the](http://reptar.github.io/docs/variables/) `theme` object. 

The `images` object doesn't expose any urls on the `theme` object.

Perhaps what might be best is to attach as an array every item in a non-processor asset configuration. So that if you just do:

```yaml
assets:
  css:
    source: ./css/main.less
  js:
    source: ./js/main.js
```

You'll have `theme.js = [ '/js/jquery.js', '/js/main.js', '/js/foo/foo.js' ]` so that in a template you can just loop over every item and render a script tag.

```html
{% for jsSrc in theme.js %}
<script type="text/javascript" src="{{jsSrc}}"></script>
{% endfor %}
```
