### ISSUE TITLE
Unable to add Markdown Plugin via Reptar Plugin

### ISSUE THREAD

**Issue by AlahmadiQ8** [reptar/reptar#68]
In version 2.3.0, you added 1638e12 to expose the Markdown instance to add extensions/plugins for it via the plugin API. 

So far I made the following plugin: [reptar-table-of-contents](https://github.com/AlahmadiQ8/reptar-table-of-contents), which is simply four lines following the example usage in 1638e12: 

```javascript
module.exports = function(Plugin, options) {
  Plugin.markdown.configure(function(md) {
    md.use(require("markdown-it-table-of-contents"), options);
  })
};
```

In my site (https://github.com/AlahmadiQ8/reptar-site), I intsall reptar-table-of-contents via npm and add the following in my _config .yml: 

```yaml
plugins:
  html-minifier:
    enabled: true
    options:
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeAttributeQuotes: true
  excerpt:
    enabled: true
  table-of-contents:
    enabled: true
    options:
      includeLevel: [2, 3]
```

Unfortunately, this still doesn't work. I'm not sure what I'm missing.. Adding [[toc]] in my markup still does not render table of contents.
